//
// Created by diana on 5/10/2020.
//

#ifndef LAB07_FILES_SERIALIZATION_JSONSERIALIZATION_H
#define LAB07_FILES_SERIALIZATION_JSONSERIALIZATION_H

#endif //LAB07_FILES_SERIALIZATION_JSONSERIALIZATION_H

class JsonSerialization
{

};