//
// Created by diana on 5/10/2020.
//

#ifndef LAB07_FILES_SERIALIZATION_XMLSERIALIZATION_H
#define LAB07_FILES_SERIALIZATION_XMLSERIALIZATION_H


class XMLSerialization {

};


#endif //LAB07_FILES_SERIALIZATION_XMLSERIALIZATION_H
